#!/bin/bash

# todo raw.githubusercontent.com 域名可能被 dns 污染,需要考虑代理模式

# Because Git submodule commands cannot operate without a work tree, they must
# be run from within $HOME (assuming this is the root of your dotfiles)
cd "$HOME"

echo "Init submodules"
yadm submodule update --recursive --init

for file in ~/.{path,exports,aliases,functions,extra}; do
	[ -r "$file" ] && [ -f "$file" ] && source "$file";
done;
unset file;


system_type=$(uname -s)


if [ "$system_type" = "Darwin" ]; then

  # install homebrew if it's missing
  if ! command -v brew >/dev/null 2>&1; then
    echo "Installing homebrew"
    /usr/bin/ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)"
  fi

  if [ -f "$HOME/.Brewfile" ]; then
    echo "Updating homebrew bundle"
    brew bundle --global

  fi
elif [ "$system_type" = "Linux" ]; then
    if command -v apt-get >/dev/null 2>&1; then
        sudo apt-get install ruby the_silver_searcher
    fi
fi


# https://stackoverflow.com/questions/7522712/how-can-i-check-if-a-command-exists-in-a-shell-script

# https://github.com/starship/starship#getting-started
if ! command -v starship >/dev/null 2>&1; then
  echo "Installing starship"
  curl -fsSL https://starship.rs/install.sh | bash
fi



# zsh 设置

# 如果没有 ZSH 环境变量,就认为 oh-my-zsh 没有安装 安装 oh-my-zsh
if [ -z "$ZSH" ]; then
	echo "安装 oh my zsh..."
	sh -c "$(curl -fsSL https://raw.githubusercontent.com/ohmyzsh/ohmyzsh/master/tools/install.sh)"
fi


autosuggestions="$ZSH/custom/plugins/zsh-autosuggestions"
if [ ! -e "$autosuggestions" ]; then
  echo "install zsh-autosuggestions plugin"
    # 安装 zsh-autosuggestions 插件
  git clone  --depth 1 https://github.com/zsh-users/zsh-autosuggestions "$autosuggestions"
fi


nvm="$ZSH/custom/plugins/zsh-nvm"
if [ ! -e "$nvm" ]; then
  echo "install zsh-nvm plugin"
    # 安装 zsh-nvms 插件
  git clone  --depth 1 https://github.com/lukechilds/zsh-nvm "$nvm"
fi

# install tmux plugins mamanger
tpm="$HOME/.tmux/plugins/tpm"
if [ ! -e "$tpm" ]; then
    echo "install tmux plugins manager"
    git clone --depth 1 https://github.com/tmux-plugins/tpm "$tpm"
fi

