["Library/Rime"]
    type = "archive"
    url = "https://github.com/iDvel/rime-ice/archive/refs/heads/main.zip"
    exact = true
    stripComponents = 1
    refreshPeriod = "24h"
[".config/nvim"]
    type = "git-repo"
    url = "https://github.com/Tomyail/nvim_conf.git"
    refreshPeriod = "24h"
[".config/alacritty/catppuccin-frappe.toml"]
    type = "file"
    url = "https://github.com/catppuccin/alacritty/raw/main/catppuccin-frappe.toml"
    refreshPeriod = "24h"
[".config/dracula/alacritty"]
    type = "archive"
    url = "https://github.com/dracula/alacritty/archive/master.tar.gz"
    exact = true
    stripComponents = 1
    refreshPeriod = "168h"
[".config/dracula/iterm"]
    type = "archive"
    url = "https://github.com/dracula/iterm/archive/master.tar.gz"
    exact = true
    stripComponents = 1
    refreshPeriod = "168h"
[".config/dracula/terminal-app"]
    type = "archive"
    url = "https://github.com/dracula/terminal-app/archive/master.tar.gz"
    exact = true
    stripComponents = 1
    refreshPeriod = "168h"
['.vimrc']
    type = "file"
    url="https://raw.githubusercontent.com/amix/vimrc/master/vimrcs/basic.vim"
    refreshPeriod = "168h"
[".oh-my-zsh"]
    type = "archive"
    url = "https://github.com/ohmyzsh/ohmyzsh/archive/master.tar.gz"
    refreshPeriod = "168h"
    exact = true
    stripComponents = 1
[".oh-my-zsh/custom/plugins/zsh-autosuggestions"]
    type = "archive"
    url = "https://github.com/zsh-users/zsh-autosuggestions/archive/master.tar.gz"
    exact = true
    stripComponents = 1
    refreshPeriod = "168h"
[".oh-my-zsh/custom/plugins/zsh-syntax-highlighting"]
    type = "archive"
    url = "https://github.com/zsh-users/zsh-syntax-highlighting/archive/master.tar.gz"
    exact = true
    stripComponents = 1
    refreshPeriod = "168h"
[".oh-my-zsh/custom/plugins/fzf-tab"]
    type = "archive"
    url = "https://github.com/Aloxaf/fzf-tab/archive/master.tar.gz"
    exact = true
    stripComponents = 1
    refreshPeriod = "168h"
[".tmux"]
    type = "archive"
    url = "https://github.com/gpakosz/.tmux/archive/master.tar.gz"
    exact = true
    stripComponents = 1
    refreshPeriod = "168h"
[".tmux/plugins/tpm"]
    type = "archive"
    stripComponents = 1
    url = "https://github.com/tmux-plugins/tpm/archive/master.tar.gz"
    refreshPeriod = "168h"
[".asdf"]
    type = "git-repo"
    url = "https://github.com/asdf-vm/asdf.git"
    exact = true
    stripComponents = 1
    refreshPeriod = "168h"
[".git-sync"]
    type = "archive"
    url = "https://github.com/simonthum/git-sync/archive/master.tar.gz"
    exact = true
    stripComponents = 1
    refreshPeriod = "168h"

